#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
435M v2 · SFT data builder (stage 1 / stage 2 corpora)
================================================
Clean code corpora (Z: codeparrot_clean / the_stack_v1 train.jsonl, {"text": ...})
  → a "signature → solution" sample stream (loss mask over the prompt span)
  → flat uint16 .bin + side-by-side uint8 mask .bin (train / val)

Sample format (**byte-aligned** with ablation/eval_cross_models.py's prompt convention)
------------------------------------------------------------------------
    prompt   = "def name(args):\\n    "      # no docstring + 4 trailing spaces
    solution = function body (no docstring, dedented, rstripped)
    stream   = prompt + solution + "\\n" + "<eos>"

    ids      = tokenizer.encode(prompt).ids + tokenizer.encode(solution+"\\n").ids + [<eos>=4]
               ^^^ must be encoded separately: eval_cross_models.generate_one() uses
                   tokenizer.encode(prompt).ids, and BPE merges the prompt's trailing spaces with
                   that does not match the evaluation convention (measured: encoding
                   'def (n):\\n    ' on its own ends in 'ĊĠĠĠĠ', while encoding it together gives 'ĊĠĠĠ'+'Ġif')
    mask     = [0]*len(prompt_ids) + [1]*(len(solution_ids)+1)   # loss only on the solution span + <eos>

    → no new tokens (the vocab is only <s>0 </s>1 <unk>2 <pad>3 <eos>4) and no chat template (G2)

Output and dataloader contract (same flat stream as pretrain_train_wsm.py)
----------------------------------------------------------------
    <split>.bin        flat uint16, length T = N*(seq_len+1)
    <split>_mask.bin   flat uint8, length T (1 = counted in loss)
    chunk_size = seq_len + 1                       # <<< not seq_len
    off = i*chunk_size
    x = ids [off : off+seq_len]
    y = ids [off+1 : off+seq_len+1]
    labels = np.where(mask[off+1 : off+seq_len+1] == 1, y, IGNORE_INDEX(-100))
    → **no padding** (the model hardcodes is_causal=True and has no attention mask, so padding would be silently attended)

packing notes: flat concatenation + fixed-length chunking (<eos> between samples), so a sample may cross a chunk.
A crossing sample's "second piece" (landing at the head of a new chunk, prompt context already cut off) is masked to 0
by default (--crossing-policy keep disables this). This is the data-side equivalent of G11's "no cross-sample continuation":
a fixed-size grid + no padding + no cross-sample continuation cannot all hold at once, so we take "no padding + mask the out-of-range piece".

Pollution filtering (sources: code-llm-project-353M/CHALLENGES.md §4.3/§4.4 + 435M-v2/pretrain_data.py L1-L6)
    L1 framework templates: Django migrations/ORM/admin/settings, Plotly validators, Flask/FastAPI, SQLAlchemy
    L2 Python 2 leftovers    L3 sphinx_conf/packaging (fatal)
    L4 tests                 L5 quality metrics (imports>60% / class+decorator>70% / comments>80% / repeated consecutive lines)
    L6 autogenerated code
    Evaluation leak (G5): drop functions sharing a name with the 5 algorithms + 6 simple tasks + HumanEval 164

Usage
----
    py -3.12 build_sft_data.py --dry-run                 # small smoke run (this file writes to data/dryrun/)
    py -3.12 build_sft_data.py --target-tokens 30000000  # real build (20–40M target)
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
import random
import re
import sys
import textwrap
import time
import warnings
from array import array
from collections import Counter
from pathlib import Path

import numpy as np

# The corpora are full of bad escapes like '\l' → compile() spams SyntaxWarning (millions of lines on a full run)
warnings.filterwarnings("ignore")

# Windows console/pipes may default to GBK → printing non-ASCII would crash (same root cause as the 9/2 incident)
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

HERE = Path(__file__).resolve().parent            # .../435M-v2/fine-tuning
PROJECT = HERE.parent                             # .../435M-v2
DEFAULT_TOKENIZER = PROJECT / "tokenizer" / "tokenizer.json"
# Raw source files for the signature corpus. Override with --sources or the
# SFT_SOURCE_1 / SFT_SOURCE_2 environment variables; the defaults are a relative layout.
DEFAULT_SOURCES = [
    os.environ.get("SFT_SOURCE_1", str(PROJECT / "data" / "raw" / "codeparrot_clean" / "train.jsonl")),
    os.environ.get("SFT_SOURCE_2", str(PROJECT / "data" / "raw" / "the_stack_v1" / "train.jsonl")),
]
HUMANEVAL_JSONL = PROJECT / "ablation" / "HumanEval.jsonl"

# ═══════════════════════════════════════════════════════════════════
# Evaluation-leak blacklist (G5): 5 algorithms + 6 simple tasks (eval_cross_models.py)
# ═══════════════════════════════════════════════════════════════════
EVAL_NAMES = {
    "fibonacci", "quicksort", "binary_search", "two_sum", "mergesort",
    "is_palindrome", "is_prime", "reverse_string", "count_vowels", "sum_list", "factorial",
}

# ═══════════════════════════════════════════════════════════════════
# Pollution mode (CHALLENGES §4.4 / pretrain_data.py)
# ═══════════════════════════════════════════════════════════════════
L1_FRAMEWORK = {
    "django_migration": [
        "migrations.RunPython", "apps.get_model(",
        "class Migration(migrations.Migration)",
        "from django.db import migrations", "schema_editor",
        "migrations.AddField", "migrations.RemoveField", "migrations.AlterField",
        "migrations.CreateModel", "migrations.DeleteModel", "migrations.RenameField",
        "django.db.migrations", "django.apps",
    ],
    "django_model": [
        "models.CharField(", "models.TextField(", "models.IntegerField(",
        "models.BooleanField(", "models.DateField(", "models.DateTimeField(",
        "models.ForeignKey(", "models.OneToOneField(", "models.ManyToManyField(",
        "models.EmailField(", "models.URLField(", "models.FileField(",
        "models.ImageField(", "models.DecimalField(", "models.FloatField(",
        "models.AutoField(", "models.SlugField(", "models.JSONField(",
        "models.UUIDField(", "models.Model", "models.CASCADE",
    ],
    "django_meta": [
        "class Meta:", "verbose_name", "db_table",
        "unique_together", "index_together", "app_label",
    ],
    "django_admin": [
        "admin.ModelAdmin", "admin.site.register", "admin.TabularInline",
        "admin.StackedInline", "list_display =", "search_fields =",
        "list_filter =", "admin.register(", "inlines =",
    ],
    "django_config": [
        "SECRET_KEY =", "DEBUG = True", "DATABASES =", "INSTALLED_APPS =",
        "MIDDLEWARE =", "AUTH_PASSWORD_VALIDATORS", "TEMPLATES =", "STATIC_URL =",
        "LANGUAGE_CODE =", "WSGI_APPLICATION =", "ROOT_URLCONF =", "ALLOWED_HOSTS =",
        "AUTH_USER_MODEL =", "LOGIN_URL =", "REST_FRAMEWORK =", "CELERY_BROKER_URL",
        "django.utils", "from django.",
    ],
    "plotly": [
        "_plotly_utils", "basevalidators", "BaseValidator", "plotly_name=",
        "edit_type=", "parent_name=", "InfoArrayValidator", "DataArrayValidator",
        "CompoundValidator", "CompoundArrayValidator", "EnumeratedValidator",
        "FlaglistValidator", "AnyValidator", "plotly.graph_objects", "plotly.io",
    ],
    "flask_fastapi": [
        "@app.route(", "@router.get(", "@router.post(", "@bp.route(",
        "@api_view(", "Flask(__name__)", "APIRouter(", "FastAPI(",
    ],
    "sqlalchemy": [
        "Column(String", "Column(Integer", "Column(Boolean", "Column(ForeignKey",
        "Column(DateTime", "declarative_base()", "__tablename__",
        "relationship(", "back_populates",
    ],
    "other_framework": [
        "django_filters", "rest_framework", "graphene.", "strawberry.",
        "factory_boy", "factory.django", "import factory",
    ],
}

L2_PYTHON2 = [
    "# -*- coding:", "#!-*- coding", "#!-*-coding", "#coding:", "# coding:",
    "from __future__ import", "unicode_literals", "print_function",
    "absolute_import", "import __builtin__", "basestring",
    "xrange(", "print >>", "except Exception, e:",
]

L3_FATAL_CONFIG = [
    "extensions = [", "master_doc =", "html_theme =", "pygments_style =",
    "from setuptools import", "install_requires=[", "entry_points={",
    "package_data={", "setup(name=", "setup(name =",
]

L4_TESTS = [
    "import unittest", "import pytest", "from unittest import", "from pytest import",
    "unittest.TestCase", "pytest.mark.", "pytest.fixture", "pytest.raises",
    "def test_", "def setUp(", "def tearDown(",
    "def setUpClass(", "def tearDownClass(",
    "self.assertEqual", "self.assertTrue", "self.assertFalse", "self.assertRaises",
    "self.assertIn", "self.assertIsNone", "self.assertIsNotNone",
    "self.assertListEqual", "self.assertDictEqual",
    "mock.patch(", "MagicMock", "@mock.patch", "@patch(",
]

L6_AUTOGEN = [
    r"\b[a-z]+_\d{4,}\b",                                              # variable name + long numeric suffix
    r"\b[0-9a-f]{32}\b",                                               # MD5
    r"\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b",  # UUID
    r"\{\{.*?\}\}",                                                    # Jinja
    r"\{% .*?%\}",
]

# the tokenizer's 5 special tokens -- **literal occurrences** of them in a sample body get encoded to special ids:
#   a stray "<eos>" in the body breaks the "sample ends with <eos>" convention, and <pad>/<unk> inject padding semantics into the stream
SPECIAL_TOKEN_TEXT = ("<s>", "</s>", "<unk>", "<pad>", "<eos>")

LOGIC_KWS = ("=", "if ", "for ", "while ", "return ", "print(", "yield ", "raise ", "assert ")

# "Templated body" normalization: string literals → S, digits → N (flattens same-shape families such as the codecs registry)
_STR_RX = re.compile(r"'(?:[^'\\\n]|\\.)*'|\"(?:[^\"\\\n]|\\.)*\"")
_NUM_RX = re.compile(r"\d+")


def template_key(body: str) -> bytes:
    return hashlib.blake2b(_NUM_RX.sub("N", _STR_RX.sub("S", body)).encode("utf-8", "replace"),
                           digest_size=8).digest()


def compile_patterns():
    return [(rx, re.compile(rx)) for rx in L6_AUTOGEN]


# ═══════════════════════════════════════════════════════════════════
# Filters
# ═══════════════════════════════════════════════════════════════════

def pollution_reason(text: str, autogen_rx) -> str | None:
    """Per-sample pollution check. Returns the matched reason (None = clean)."""
    for label, pats in L1_FRAMEWORK.items():
        for p in pats:
            if p in text:
                return f"L1_{label}:{p[:44]}"
    for p in L2_PYTHON2:
        if p in text:
            return f"L2_python2:{p[:44]}"
    for p in L3_FATAL_CONFIG:
        if p in text:
            return f"L3_config:{p[:44]}"
    for p in L4_TESTS:
        if p in text:
            return f"L4_test:{p[:44]}"
    for rx, c in autogen_rx:
        if len(c.findall(text)) >= 3:
            return f"L6_autogen:{rx[:44]}"
    return None


def quality_reason(body: str) -> str | None:
    """L5 quality metrics (computed on the solution body)."""
    lines = body.split("\n")
    total = len(lines)
    if total < 2:
        return "L5_too_few_lines"
    non_comment = [l for l in lines if l.strip() and not l.strip().startswith("#")]
    effective = len(non_comment)
    if effective < 2:
        return f"L5_effective={effective}"

    import_count = sum(1 for l in non_comment if l.strip().startswith(("import ", "from ")))
    if import_count / effective > 0.6:
        return f"L5_import_ratio={import_count/effective:.0%}"

    class_count = sum(1 for l in non_comment
                      if l.strip().startswith(("class ", "@staticmethod", "@classmethod", "@property")))
    decorator_count = sum(1 for l in non_comment
                          if l.strip().startswith("@")
                          and not l.strip().startswith(("@staticmethod", "@classmethod", "@property")))
    if (class_count + decorator_count) / effective > 0.7:
        return f"L5_class_ratio={(class_count+decorator_count)/effective:.0%}"

    comment_ratio = sum(1 for l in lines if l.strip().startswith("#")) / total
    if comment_ratio > 0.8:
        return f"L5_comment_ratio={comment_ratio:.0%}"

    consec = 0
    stripped = [l.strip() for l in non_comment]
    for i in range(1, len(stripped)):
        if stripped[i] and stripped[i] == stripped[i - 1]:
            consec += 1
            if consec >= 3:
                return "L5_consecutive_repeat"
        else:
            consec = 0

    if sum(1 for l in non_comment if any(k in l for k in LOGIC_KWS)) < 1:
        return "L5_no_logic_line"
    return None


# ═══════════════════════════════════════════════════════════════════
# Candidate extraction: clean corpus → (prompt, solution)
# ═══════════════════════════════════════════════════════════════════

def iter_func_nodes(tree, allow_methods: bool):
    def walk(body):
        for node in body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                yield node
            elif allow_methods and isinstance(node, ast.ClassDef):
                yield from walk(node.body)
    yield from walk(tree.body)


def is_docstring_first(node) -> bool:
    b = node.body[0]
    return (isinstance(b, ast.Expr) and isinstance(b.value, ast.Constant)
            and isinstance(b.value.value, str))


def split_signature_body(src_lines, node, docstring_mode="strip"):
    """Return (prompt_text, solution_text); None when it is not a "single-line signature + body on the next line".

    The indentation subtlety: the prompt ends with "\\n    " (4 spaces) and those 4 spaces only indent the **first** line,
      so the solution body must be "dedented, then 4 spaces re-added to every line but the first",
      otherwise lines outside the def fall back to column 0 ('return' outside function).
    """
    first = node.body[0]
    # the def and the body's first statement must be on adjacent lines (excludes `def f(): return 1` and multi-line signatures)
    if first.lineno != node.lineno + 1:
        return None
    if node.lineno < 1 or node.lineno > len(src_lines):   # bounds check (leftover node from an exception / pre-normalization)
        return None
    sig = src_lines[node.lineno - 1]
    if not sig.rstrip().endswith(":"):
        cut = sig.split("#")[0].rstrip()          # trailing comment `def f(x):  # noqa`
        if cut.endswith(":"):
            sig = cut
        else:
            return None
    sig_core = sig.strip()
    if not re.match(r"^(async\s+def|def)\s", sig_core):
        return None

    start = first.lineno
    if is_docstring_first(node):
        if docstring_mode == "reject":
            return None
        if len(node.body) < 2:                    # the body is only a docstring → no solution
            return None
        start = node.body[1].lineno

    body_lines = src_lines[start - 1: node.end_lineno]
    ded = textwrap.dedent("\n".join(body_lines)).split("\n")
    out = [ded[0].rstrip()]
    out.extend(("    " + l.rstrip()) if l.strip() else "" for l in ded[1:])
    body = "\n".join(out).rstrip()
    if not body.strip():
        return None
    return sig_core + "\n    ", body


# ═══════════════════════════════════════════════════════════════════
# Writers
# ═══════════════════════════════════════════════════════════════════

class BinWriter:
    """flat uint16 ids + side-by-side uint8 loss-mask, positioned as written (crossing mask done inline)."""

    def __init__(self, out_dir: Path, name: str, seq_len: int):
        self.C = seq_len + 1
        self.name = name
        self.bin_path = Path(out_dir) / f"{name}.bin"
        self.mask_path = Path(out_dir) / f"{name}_mask.bin"
        self.f = open(self.bin_path, "wb")
        self.mf = open(self.mask_path, "wb")
        self.total = 0          # tokens written so far (including an unaligned tail)
        self.n_samples = 0
        self.n_cross = 0        # samples crossing a chunk that were masked

    def write_sample(self, ids: array, mask: bytes, policy: str = "mask"):
        off = self.total
        L = len(ids)
        B = (off // self.C) * self.C
        lim = B + self.C - off                       # local index + 1 of the last usable token in this chunk
        if L > lim:                                  # sample crosses the chunk → its tail piece has orphan context
            self.n_cross += 1
            if policy == "mask":
                m = bytearray(mask)
                for j in range(max(lim, 0), L):
                    m[j] = 0
                mask = bytes(m)
        np.frombuffer(ids, dtype=np.uint16).tofile(self.f)
        self.mf.write(mask)
        self.total += L
        self.n_samples += 1

    def finalize(self) -> int:
        usable = (self.total // self.C) * self.C
        self.f.flush()
        self.mf.flush()
        if self.total > usable:                      # drop a tail shorter than one chunk (same policy as pretrain_data.py)
            self.f.truncate(usable * 2)
            self.mf.truncate(usable)
        self.f.close()
        self.mf.close()
        return usable


# ═══════════════════════════════════════════════════════════════════
# Verification: read the bin back and confirm length / mask / boundaries
# ═══════════════════════════════════════════════════════════════════

def verify_outputs(out_dir: Path, names, seq_len: int, tokenizer, n_probe: int = 3,
                   eos_id: int = 4):
    C = seq_len + 1
    prompt_rx = re.compile(r"^(async )?def [^\n]*:\n    $")
    rep = {}
    for name in names:
        bp = out_dir / f"{name}.bin"
        mp = out_dir / f"{name}_mask.bin"
        if not bp.exists() or not mp.exists():
            continue
        n_ids = bp.stat().st_size // 2
        n_mask = mp.stat().st_size
        ids = np.memmap(bp, dtype=np.uint16, mode="r")
        mask = np.fromfile(mp, dtype=np.uint8)
        chunks = n_ids // C
        ones = int(mask.sum())

        # ── per sample (split on <eos>), vectorized check that the mask is strictly 0^p 1^q 0^r ──
        N = int(n_ids)
        eos_pos = np.flatnonzero(np.asarray(ids, dtype=np.uint16) == eos_id)
        starts = np.concatenate((np.zeros(1, dtype=np.int64), eos_pos.astype(np.int64) + 1))
        ends = np.concatenate((eos_pos.astype(np.int64), np.zeros(1, dtype=np.int64)))
        if len(eos_pos) > 0:
            ends[-1] = N - 1
            m = mask.astype(np.int8)
            ar = np.arange(N, dtype=np.int32)
            # first_one[i] = index of the first 1 at or after i; last_one[i] = index of the last 1 at or before i
            first_one = np.minimum.accumulate(np.where(m == 1, ar, np.int32(N))[::-1])[::-1]
            last_one = np.maximum.accumulate(np.where(m == 1, ar, np.int32(-1)))
            f = first_one[starts]
            l = last_one[ends]
            cum = np.concatenate((np.zeros(1, dtype=np.int64), np.cumsum(m, dtype=np.int64)))
            n_ones = cum[ends + 1] - cum[starts]
            empty = f > ends                       # the whole sample has no loss (pure context)
            dense = (n_ones == (l - f + 1)) & ~empty
            tail_masked = (l < ends) & ~empty       # tail zeroed by the crossing policy
            ok_boundary = np.ones(len(ends), dtype=bool)
            if tail_masked.any():
                ok_boundary[tail_masked] = ((l + 1)[tail_masked] % C) == 0
            n_s = len(eos_pos)                      # only "complete" samples are counted (the last one is a truncated fragment)
            sl = slice(0, n_s)
            invalid = int((~(empty | (dense & ok_boundary)))[sl].sum())
            n_empty = int(empty[sl].sum())
            n_tail = int(tail_masked[sl].sum())
            n_bad_boundary = int((tail_masked & ~ok_boundary)[sl].sum())
        else:
            invalid = n_empty = n_tail = n_bad_boundary = 0

        # ── chunk level: an unclean chunk head must be a "masked tail piece" ──
        bad_second = int((mask[1:chunks * C:C] == 1).sum())
        starts_mid = int((mask[0:chunks * C:C] == 1).sum())
        probes, clean_heads = [], 0
        for i in range(chunks):
            off = i * C
            if mask[off] != 0:
                continue
            seg = mask[off: off + seq_len + 1]
            nz = np.flatnonzero(seg == 1)
            if len(nz) == 0:
                continue
            j = int(nz[0])
            prompt_txt = tokenizer.decode(ids[off: off + j].tolist())
            ok = bool(prompt_rx.match(prompt_txt))
            clean_heads += int(ok)
            if len(probes) < n_probe and ok:
                probes.append({
                    "chunk": i,
                    "prompt": prompt_txt,
                    "solution_head": tokenizer.decode(ids[off + j: off + j + 24].tolist()),
                    "loss_tokens_in_chunk": int(seg.sum()),
                })

        rep[name] = {
            "bin_tokens": int(n_ids),
            "mask_tokens": int(n_mask),
            "aligned": bool(n_ids == n_mask and n_ids % C == 0),
            "chunks": int(chunks),
            "loss_tokens": ones,
            "loss_ratio": round(ones / max(n_ids, 1), 4),
            "samples_in_bin": int(len(eos_pos)),
            "samples_with_invalid_mask": invalid,
            "samples_with_zero_loss": n_empty,
            "samples_tail_masked_crossing": n_tail,
            "samples_tail_masked_not_at_block_boundary": n_bad_boundary,
            "has_pad_or_unk": bool(((np.asarray(ids) == 3) | (np.asarray(ids) == 2)).any()),
            "chunks_with_unmasked_second_label": bad_second,
            "chunks_starting_mid_solution": starts_mid,
            "chunks_with_clean_def_prompt_head": clean_heads,
            "probes": probes,
        }
    return rep


# ═══════════════════════════════════════════════════════════════════
# Main flow
# ═══════════════════════════════════════════════════════════════════

def parse_args(argv=None):
    p = argparse.ArgumentParser(
        description="435M v2 SFT data build: clean corpus → signature→solution sample stream (with prompt loss mask)",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    p.add_argument("--sources", nargs="+", default=list(DEFAULT_SOURCES))
    p.add_argument("--tokenizer", default=str(DEFAULT_TOKENIZER))
    p.add_argument("--out-dir", default=None, help="default fine-tuning/data (data/dryrun in dry-run)")
    p.add_argument("--target-tokens", type=int, default=30_000_000)
    p.add_argument("--val-ratio", type=float, default=0.02)
    p.add_argument("--seq-len", type=int, default=1024)
    p.add_argument("--min-chars", type=int, default=50)
    p.add_argument("--max-chars", type=int, default=1000)
    p.add_argument("--min-effective-lines", type=int, default=3)
    p.add_argument("--max-doc-chars", type=int, default=100_000)
    p.add_argument("--pool-tokens", type=int, default=2_000_000, help="in-memory pool size (shuffle + write granularity)")
    p.add_argument("--per-source-tokens", type=int, default=None,
                   help="max tokens contributed per source (default target/n_sources, keeps the mix even; 0 = unlimited)")
    p.add_argument("--review-n", type=int, default=200, help="number of rows in the spot-check file")
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--allow-methods", action="store_true", help="allow in-class methods (the prompt loses its indentation)")
    p.add_argument("--allow-async", action="store_true")
    p.add_argument("--docstring-mode", choices=["strip", "reject"], default="strip",
                   help="strip=drop the docstring and keep the rest of the solution; reject=drop the whole sample (G4 requires docstring-free samples)")
    p.add_argument("--max-template-repeats", type=int, default=5,
                   help="max occurrences of the same templated body (same shape after string/digit normalization); beyond this the sample is dropped")
    p.add_argument("--no-compile-check", action="store_true")
    p.add_argument("--no-eos-newline", action="store_true", help="no newline between the solution and <eos>")
    p.add_argument("--crossing-policy", choices=["mask", "keep"], default="mask")
    p.add_argument("--no-blacklist", action="store_true", help="do not drop functions named like the evaluation ones (not recommended)")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--dry-scan-lines", type=int, default=150_000)
    p.add_argument("--dry-target-tokens", type=int, default=1_500_000)
    p.add_argument("--dry-pool-tokens", type=int, default=500_000)
    p.add_argument("--log-every", type=int, default=100_000)
    p.add_argument("--preview", type=int, default=3, help="number of samples printed to the console")
    return p.parse_args(argv)


def build_blacklist(no_blacklist: bool):
    if no_blacklist:
        return set()
    names = set(EVAL_NAMES)
    if HUMANEVAL_JSONL.exists():
        try:
            with open(HUMANEVAL_JSONL, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        o = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    ep = o.get("entry_point")
                    if ep:
                        names.add(str(ep))
        except OSError:
            pass
    return names


def main(argv=None):
    args = parse_args(argv)
    t0 = time.time()

    dry = args.dry_run
    if args.out_dir:
        out_dir = Path(args.out_dir)
    else:
        out_dir = HERE / "data" / "dryrun" if dry else HERE / "data"
    out_dir.mkdir(parents=True, exist_ok=True)

    target = args.dry_target_tokens if dry else args.target_tokens
    pool_tokens = args.dry_pool_tokens if dry else args.pool_tokens
    scan_limit = args.dry_scan_lines if dry else None

    # ── tokenizer ──
    from tokenizers import Tokenizer
    tok = Tokenizer.from_file(str(args.tokenizer))
    vocab = tok.get_vocab_size()
    eos_id = tok.token_to_id("<eos>")
    if eos_id is None:
        raise SystemExit("[FATAL] tokenizer has no <eos>")
    if vocab > 65536:
        raise SystemExit(f"[FATAL] vocab={vocab} exceeds uint16")
    print(f"[TOK] {args.tokenizer}  vocab={vocab}  <eos>={eos_id}")

    blacklist = build_blacklist(args.no_blacklist)
    autogen_rx = compile_patterns()
    print(f"[BL] evaluation-leak blacklist: {len(blacklist)} function names"
          f"{' (disabled)' if args.no_blacklist else ''}")

    # ── output ──
    w_train = BinWriter(out_dir, "sft_train", args.seq_len)
    w_val = BinWriter(out_dir, "sft_val", args.seq_len)
    rng = random.Random(args.seed)
    pool, val_pool, review = [], [], []
    pool_n = val_pool_n = 0
    seen = set()
    tpl_counts = {}
    st = Counter()
    per_source = {}

    def flush(pool, writer):
        if not pool:
            return
        rng.shuffle(pool)
        for ids, mask in pool:
            writer.write_sample(ids, mask, args.crossing_policy)
        pool.clear()

    print(f"[RUN] {'DRY-RUN' if dry else 'FULL'}  target={target/1e6:.1f}M tokens  "
          f"out={out_dir}  seq_len={args.seq_len}  val_ratio={args.val_ratio}  "
          f"scan_limit={scan_limit}")

    stop = False
    n_src = max(len(args.sources), 1)
    if args.per_source_tokens is None:
        per_source_quota = int(target / n_src)
    else:
        per_source_quota = args.per_source_tokens or None
    print(f"[MIX] per-source quota = {per_source_quota if per_source_quota is None else f'{per_source_quota/1e6:.1f}M'}"
          f"  ({n_src} sources, target={target/1e6:.1f}M)")

    for src in args.sources:
        if stop:
            break
        src_path = Path(src)
        if not src_path.exists():
            print(f"[WARN] source does not exist, skipping: {src_path}")
            st["source_missing"] += 1
            continue
        s = Counter()
        s_lines = 0
        src_tokens = 0
        src_name = f"{src_path.parent.name}/{src_path.name}"   # both sources are called train.jsonl, so the parent dir is required
        print(f"\n[SRC] {src_path}  ({src_path.stat().st_size/1e9:.1f} GB)")
        # read-only, streaming, explicit utf-8 (the jsonl files are huge and must never be loaded whole)
        with open(src_path, "r", encoding="utf-8", errors="replace") as f:
            for line in f:
                s_lines += 1
                st["lines"] += 1
                if scan_limit and s_lines > scan_limit:
                    s["scan_limit_reached"] = 1
                    break
                if w_train.total >= target:
                    stop = True
                    break
                if per_source_quota and src_tokens >= per_source_quota:
                    break
                if not line.strip():
                    st["reject_empty_line"] += 1
                    continue
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    st["reject_json_error"] += 1
                    continue
                text = rec.get("text") or rec.get("content") or ""
                if not isinstance(text, str) or not text.strip():
                    st["reject_no_text_field"] += 1
                    continue
                if "\r" in text:      # normalize newlines: ast treats \r as a line terminator too while downstream splits on \n → used to overflow lineno
                    text = text.replace("\r\n", "\n").replace("\r", "\n")
                if "\ufffd" in text:
                    st["reject_bad_utf8"] += 1
                    continue
                if len(text) > args.max_doc_chars:
                    st["reject_doc_too_long"] += 1
                    continue
                if "def " not in text:
                    st["reject_no_def_substring"] += 1
                    continue
                try:
                    tree = ast.parse(text)
                except (SyntaxError, ValueError, MemoryError, RecursionError):
                    st["reject_syntax_error"] += 1
                    continue
                s["docs_parsed"] += 1
                src_lines = text.split("\n")
                for node in iter_func_nodes(tree, args.allow_methods):
                    st["candidate_defs"] += 1
                    if isinstance(node, ast.AsyncFunctionDef) and not args.allow_async:
                        st["rej_async"] += 1
                        continue
                    name = node.name
                    if name in blacklist:
                        st["rej_eval_leak_name"] += 1
                        continue
                    has_ds = is_docstring_first(node)
                    if has_ds and args.docstring_mode == "reject":
                        st["rej_docstring"] += 1
                        continue
                    sb = split_signature_body(src_lines, node, args.docstring_mode)
                    if sb is None:
                        st["rej_bad_signature"] += 1
                        continue
                    if has_ds:
                        st["docstring_stripped"] += 1
                    prompt, body = sb
                    if len(prompt) + len(body) > args.max_chars:
                        st["rej_too_long_chars"] += 1
                        continue
                    if len(prompt) + len(body) < args.min_chars:
                        st["rej_too_short_chars"] += 1
                        continue
                    eff = sum(1 for l in body.split("\n")
                              if l.strip() and not l.strip().startswith("#"))
                    if eff < args.min_effective_lines:
                        st["rej_too_few_effective_lines"] += 1
                        continue
                    sample_text = prompt + body
                    hit_special = next((t for t in SPECIAL_TOKEN_TEXT if t in sample_text), None)
                    if hit_special:
                        st["rej_special_token_literal"] += 1
                        continue
                    reason = pollution_reason(sample_text, autogen_rx)
                    if reason:
                        st[f"rej_{reason.split(':')[0]}"] += 1
                        st["rej_pollution_total"] += 1
                        continue
                    qr = quality_reason(body)
                    if qr:
                        st[f"rej_{qr.split('=')[0]}"] += 1
                        st["rej_quality_total"] += 1
                        continue
                    if not args.no_compile_check:
                        try:
                            compile(prompt + body, "<sft>", "exec")
                        except (SyntaxError, ValueError):
                            st["rej_compile_fail"] += 1
                            continue
                    tail = "" if args.no_eos_newline else "\n"
                    pid = tok.encode(prompt).ids
                    sid = tok.encode(body + tail).ids
                    n = len(pid) + len(sid) + 1
                    if n > args.seq_len:
                        st["rej_too_long_tokens"] += 1
                        continue
                    ids = array("H", pid)
                    ids.extend(sid)
                    ids.append(eos_id)
                    mask = b"\x00" * len(pid) + b"\x01" * (len(sid) + 1)

                    digest = hashlib.blake2b(sample_text.encode("utf-8", "replace"),
                                             digest_size=8).digest()
                    if digest in seen:
                        st["rej_duplicate"] += 1
                        continue
                    tkey = template_key(body)
                    if tpl_counts.get(tkey, 0) >= args.max_template_repeats:
                        st["rej_template_repeat"] += 1
                        continue
                    seen.add(digest)
                    tpl_counts[tkey] = tpl_counts.get(tkey, 0) + 1
                    h = int.from_bytes(digest, "big")
                    st["accepted"] += 1
                    st["accepted_tokens"] += n
                    st["accepted_prompt_tokens"] += len(pid)
                    src_tokens += n
                    is_val = (h % 10000) < int(args.val_ratio * 10000)
                    if is_val:
                        val_pool.append((ids, mask))
                        val_pool_n += n
                        st["accepted_val"] += 1
                    else:
                        pool.append((ids, mask))
                        pool_n += n
                        st["accepted_train"] += 1
                    if len(review) < args.review_n:
                        review.append({"split": "val" if is_val else "train",
                                       "prompt": prompt, "solution": body,
                                       "prompt_tokens": len(pid), "solution_tokens": len(sid) + 1,
                                       "total_tokens": n, "source": src_name})
                    elif args.review_n > 0:
                        # reservoir sampling: makes the 200 spot-check rows uniform over the whole run (otherwise only the head of the first source)
                        j = rng.randrange(st["accepted"])
                        if j < args.review_n:
                            review[j] = {"split": "val" if is_val else "train",
                                         "prompt": prompt, "solution": body,
                                         "prompt_tokens": len(pid),
                                         "solution_tokens": len(sid) + 1,
                                         "total_tokens": n, "source": src_name}
                    if pool_n >= pool_tokens:
                        pool_n = 0
                        flush(pool, w_train)
                    if val_pool_n >= pool_tokens:
                        val_pool_n = 0
                        flush(val_pool, w_val)
                if st["lines"] % args.log_every == 0:
                    print(f"  ...lines={st['lines']:,} accepted={st['accepted']:,} "
                          f"raw_tokens={w_train.total/1e6:.2f}M "
                          f"({time.time()-t0:.0f}s)")
        s["tokens"] = src_tokens
        per_source[src_name] = dict(s)
        print(f"  [SRC-DONE] {src_name}: lines={s_lines:,} "
              f"docs_parsed={s['docs_parsed']:,} src_tokens={src_tokens:,} "
              f"accepted_total={st['accepted']:,}")

    flush(pool, w_train)
    flush(val_pool, w_val)
    usable_train = w_train.finalize()
    usable_val = w_val.finalize()

    # ── verification ──
    verify = verify_outputs(out_dir, ["sft_train", "sft_val"], args.seq_len, tok, eos_id=eos_id)

    # ── review file ──
    review_path = out_dir / "samples_review.jsonl"
    with open(review_path, "w", encoding="utf-8") as f:
        for r in review:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")

    # ── interface doc for the sft_train.py author (lives next to the bin, single source of truth) ──
    C = args.seq_len + 1
    fmt_doc = f"""# SFT data format (generated by build_sft_data.py, do not edit by hand)

Two files per split, aligned token by token:

| file | dtype | meaning |
|---|---|---|
| `sft_train.bin` / `sft_val.bin` | uint16 | flat token stream |
| `sft_train_mask.bin` / `sft_val_mask.bin` | uint8 | 1 = counted in loss, 0 = ignored |

Length `T = N * (seq_len + 1)`; this directory has `seq_len={args.seq_len}` → **chunk_size = {C}** (not {args.seq_len}).

## Sample stream

```
def name(args):        <- prompt: tokenizer.encode(prompt).ids (byte-identical to ablation/eval_cross_models.py
    <solution>              generate_one() = no docstring + 4 trailing spaces)
<eos>                  <- loss span = solution + <eos>; prompt span mask=0
```
Samples are concatenated directly (**no padding**; the model hardcodes is_causal=True, so padding would be silently attended);
a crossing sample's tail piece (landing at the head of the next chunk, prompt context already lost) is masked to zero.

## Dataloader contract

```python
ids  = np.memmap(bin_path, dtype=np.uint16, mode="r")
mask = np.fromfile(mask_path, dtype=np.uint8)
C = seq_len + 1                      # {C}
for i in range(len(ids) // C):
    off = i * C
    x = torch.from_numpy(ids[off:off+seq_len].astype(np.int64))
    y = torch.from_numpy(ids[off+1:off+seq_len+1].astype(np.int64))
    keep = torch.from_numpy(mask[off+1:off+seq_len+1].astype(bool))
    labels = torch.where(keep, y, torch.full_like(y, -100))
# loss = F.cross_entropy(logits.view(-1, V), labels.view(-1), ignore_index=-100)
```
Multiple passes (epochs) = iterate the whole bin again; **do not use `--mode online`** (353M had a resume incident that re-read from file 0).

## Invariants (self-checked at build time)

- `len(ids) == len(mask) == N*{C}`, and `N*{C} == T`
- each sample's mask is strictly `0^p 1^q 0^r`; when `0^r` is non-empty its start is a multiple of {C} (the crossing-tail masking policy)
- the stream contains no `<pad>(3)` / `<unk>(2)`; `<eos>` literals are already stripped from bodies at build time
- every sample's `prompt+solution` passes `compile()`
"""
    with open(out_dir / "README_FORMAT.md", "w", encoding="utf-8") as f:
        f.write(fmt_doc)

    # ── stats / meta ──
    reject = {k: v for k, v in sorted(st.items())
              if k.startswith("rej_") or k.startswith("reject_")}
    cross_info = {"train_crossed_samples": w_train.n_cross, "val_crossed_samples": w_val.n_cross,
                  "policy": args.crossing_policy}
    common = {
        "seq_len": args.seq_len,
        "chunk_size": args.seq_len + 1,
        "dtype": "uint16",
        "mask_dtype": "uint8",
        "mask_semantics": "1 = counted in loss (solution span + <eos>); 0 = prompt span / crossing tail / tail truncation",
        "sample_format": "prompt='def name(args):\\n    '  +  solution(body)  +  '<eos>'",
        "prompt_encoding": "tokenizer.encode(prompt).ids (same source as eval_cross_models.generate_one, byte-aligned)",
        "dataloader_contract": (
            "ids=np.memmap(bin,dtype=np.uint16); mask=np.fromfile(mask_bin,dtype=np.uint8); "
            "C=seq_len+1; for off in range(0,len(ids),C): "
            "x=ids[off:off+seq_len]; y=ids[off+1:off+seq_len+1]; "
            "labels=np.where(mask[off+1:off+seq_len+1]==1,y,-100)"),
        "no_padding": True,
        "sources": [str(s) for s in args.sources],
        "config": {
            "target_tokens": target, "val_ratio": args.val_ratio,
            "min_chars": args.min_chars, "max_chars": args.max_chars,
            "min_effective_lines": args.min_effective_lines,
            "allow_methods": args.allow_methods, "allow_async": args.allow_async,
            "docstring_mode": args.docstring_mode,
            "max_template_repeats": args.max_template_repeats,
            "eos_newline": not args.no_eos_newline, "compile_check": not args.no_compile_check,
            "blacklist_size": len(blacklist), "seed": args.seed, "dry_run": dry,
        },
        "rejection": reject,
        "crossing": cross_info,
        "created": time.strftime("%Y-%m-%dT%H:%M:%S"),
    }

    for name, writer, usable in (("sft_train", w_train, usable_train), ("sft_val", w_val, usable_val)):
        v = verify.get(name, {})
        meta = dict(common)
        meta.update({
            "split": name.split("_")[-1],
            "total_tokens": int(usable),
            "num_chunks": int(usable // (args.seq_len + 1)),
            "num_samples_written": writer.n_samples,
            "samples_in_bin": v.get("samples_in_bin"),
            "samples_dropped_at_tail_truncation": (writer.n_samples - (v.get("samples_in_bin") or 0)),
            "crossing_counter": writer.n_cross,
            "loss_tokens": v.get("loss_tokens"),
            "loss_ratio": v.get("loss_ratio"),
            "verified": v,
        })
        with open(out_dir / f"{name}_meta.json", "w", encoding="utf-8") as f:
            json.dump(meta, f, ensure_ascii=False, indent=2)

    report = dict(common)
    report.update({
        "elapsed_s": round(time.time() - t0, 1),
        "counters": {k: v for k, v in sorted(st.items()) if not k.startswith(("rej_", "reject_"))},
        "per_source": per_source,
        "splits": {k: {"tokens": (int(usable_train) if k == "sft_train" else int(usable_val)),
                       "chunks": verify.get(k, {}).get("chunks"),
                       "samples": (w_train.n_samples if k == "sft_train" else w_val.n_samples),
                       "loss_tokens": verify.get(k, {}).get("loss_tokens")}
                   for k in ("sft_train", "sft_val")},
        "verify": verify,
    })
    with open(out_dir / "build_stats.json", "w", encoding="utf-8") as f:
        json.dump(report, f, ensure_ascii=False, indent=2)
    # README convention: build logs go to fine-tuning/logs/
    try:
        log_dir = HERE / "logs"
        log_dir.mkdir(parents=True, exist_ok=True)
        stamp = time.strftime("%Y%m%d_%H%M%S")
        with open(log_dir / f"build_sft_data_{stamp}{'_dryrun' if dry else ''}.json",
                  "w", encoding="utf-8") as f:
            json.dump(report, f, ensure_ascii=False, indent=2)
    except OSError as e:
        print(f"[WARN] failed to write logs/: {e}")

    # ── console report ──
    print(f"\n{'='*72}\n[REJECTION] rejection counters")
    for k, v in sorted(reject.items(), key=lambda kv: -kv[1]):
        print(f"  {k:38s} {v:>12,}")
    print(f"\n[COUNTERS]")
    for k, v in sorted(st.items()):
        if not k.startswith(("rej_", "reject_")) and not k.startswith("_"):
            print(f"  {k:38s} {v:>12,}")
    print(f"\n[VERIFY]")
    for name, v in verify.items():
        print(f"  {name}: tokens={v['bin_tokens']:,} chunks={v['chunks']:,} "
              f"loss_tokens={v['loss_tokens']:,} ({v['loss_ratio']:.1%}) aligned={v['aligned']}")
        print(f"    samples_in_bin={v['samples_in_bin']:,} invalid_mask={v['samples_with_invalid_mask']} "
              f"zero_loss={v['samples_with_zero_loss']} "
              f"tail_masked={v['samples_tail_masked_crossing']} "
              f"(off_grid={v['samples_tail_masked_not_at_block_boundary']}) "
              f"pad/unk={v['has_pad_or_unk']}")
        print(f"    bad_2nd_label={v['chunks_with_unmasked_second_label']} "
              f"chunk_head_mid_solution={v['chunks_starting_mid_solution']} "
              f"clean_def_head={v['chunks_with_clean_def_prompt_head']}")
    print(f"  crossing_counter: train={w_train.n_cross} val={w_val.n_cross}")
    for name, v in verify.items():
        for p in v["probes"][:2]:
            if "prompt" in p:
                print(f"  [{name} chunk {p['chunk']}] prompt={p['prompt']!r}")
                print(f"      solution_head={p['solution_head']!r}")

    print(f"\n[PREVIEW] first {args.preview} samples:")
    for r in review[:args.preview]:
        print(f"  --- {r['split']}  prompt_tokens={r['prompt_tokens']} "
              f"sol_tokens={r['solution_tokens']} total={r['total_tokens']}")
        print("  " + ("\n  ".join((r["prompt"] + r["solution"]).split("\n")[:8])))
    print(f"\n[OUT] {out_dir}")
    print(f"      sft_train.bin ({usable_train:,} tok) / sft_train_mask.bin")
    print(f"      sft_val.bin   ({usable_val:,} tok) / sft_val_mask.bin")
    print(f"      *_meta.json / build_stats.json / {review_path.name} ({len(review)} rows)")
    print(f"[DONE] {time.time()-t0:.1f}s   {'DRY-RUN (not the full run)' if dry else 'FULL'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
