#!/usr/bin/env python3
"""
══════════════════════════════════════════════════════════════════════
Ablation 2 - Data quality (Data Quality Ablation) * highest priority
══════════════════════════════════════════════════════════════════════

Question: is data cleaning more important than more data?

Arms (CodeLM-435M, 22L, d_ff=4096):
  Model A (No Filter)  - raw GitHub code, only .py + >=50 chars
  Model B (Filtered)   - full L1-L6 filtering

L1-L6 filter pipeline (from pretrain_data.py):
  L1: drop framework/library scaffolding (Django, Flask, SQLAlchemy, etc.)
  L2: drop Python 2 code
  L3: drop .py files that are really config
  L4: drop pure test files
  L5: quality metrics (comment rate, mean line width, function size)
  L6: drop autogenerated code (autogenerated, astor, etc.)

Controls:
  - same architecture (435M)
  - same training tokens (50M each)
  - same hyperparameters
  - all trained from scratch

Metrics:
  - validation loss curve
  - training efficiency (effective tokens/sec)
  - later: HumanEval pass@k

Usage:
  python ablation/ablation_data_quality.py --mode nofilter
  python ablation/ablation_data_quality.py --mode filtered
  python ablation/ablation_data_quality.py --mode compare   # run both arms in order
══════════════════════════════════════════════════════════════════════
"""

import sys, argparse
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from ablation_common import *

# config
PARQUET_DIR = None  # raw unfiltered parquet; set via --parquet-dir at runtime
VAL_BIN = DATA_DIR / "all" / "val.bin"  # shared val set (filtered)

# 435M architecture
MODEL_435M = {
    "d_model": 1024,
    "num_layers": 22,
    "num_heads": 16,
    "d_ff": 4096,
    "vocab_size": 32000,
}

# 50M tokens is enough to compare filter effects
# raise to 200M for a stronger signal
TARGET_TOKENS = 50_000_000


def main():
    parser = argparse.ArgumentParser(
        description="Data quality ablation - CodeLM-435M")
    parser.add_argument("--mode", choices=["nofilter", "filtered", "compare"],
                        default="compare", help="which arm to run")
    parser.add_argument("--parquet-dir", type=str, default=None,
                        help="raw unfiltered parquet dir (required for data_quality mode)")
    parser.add_argument("--lr", type=float, default=2.5e-4)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--grad-accum", type=int, default=4)
    parser.add_argument("--seq-len", type=int, default=1024)
    parser.add_argument("--save-every", type=int, default=200)
    parser.add_argument("--eval-every", type=int, default=200)
    parser.add_argument("--tokens", type=int, default=TARGET_TOKENS,
                       help=f"training tokens (default {TARGET_TOKENS/1e6:.0f}M)")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    tokenizer = load_tokenizer()

    # validation set
    val_path = str(VAL_BIN) if VAL_BIN.exists() else None
    if not VAL_BIN.exists():
        print("[VAL] [WARN] no validation set, skipping eval")
    else:
        val_path = str(VAL_BIN)

    modes = ["nofilter", "filtered"] if args.mode == "compare" else [args.mode]

    results = {}
    for mode in modes:
        apply_filter = (mode == "filtered")
        exp_name = f"ablation_data_quality_{mode}"
        exp_dir = ABLATION_DIR / exp_name

        filter_desc = "L1-L6 fully on" if apply_filter else "only .py + >=50 chars"
        print(f"\n{'='*60}")
        print(f"[INFO] data quality ablation: {mode}")
        print(f"  filter policy: {filter_desc}")
        print(f"  target: {args.tokens/1e6:.0f}M tokens")
        print(f"{'='*60}")

        if not args.parquet_dir:
            print("[FAIL] data_quality mode requires --parquet-dir for raw parquet")
            return 1
        data_gen = create_online_dataloader(
            args.parquet_dir, tokenizer, seq_len=args.seq_len,
            max_tokens=args.tokens, apply_filter=apply_filter,
        )

        config = ModelConfig(**MODEL_435M)
        config.max_seq_len = args.seq_len

        state = run_ablation_training(
            exp_name=exp_name,
            exp_dir=str(exp_dir),
            data_gen=data_gen,
            val_bin=val_path,
            config=config,
            resume_from=None,  # train from scratch for a clean comparison
            batch_size=args.batch_size,
            grad_accum=args.grad_accum,
            lr=args.lr,
            max_tokens=args.tokens,
            save_every=args.save_every,
            eval_every=args.eval_every,
            log_every=10,
            seed=args.seed,
        )

        results[mode] = {
            "final_step": state["step"],
            "total_tokens": state["total_tokens"],
            "best_val_loss": state.get("best_val_loss", float("inf")),
        }

    # comparison report
    if len(results) == 2:
        print(f"\n{'='*60}")
        print("\n[INFO] data quality ablation - comparison")
        print(f"{'='*60}")
        for mode, r in results.items():
            print(f"  {mode:12s}: step={r['final_step']:6d}, "
                  f"tokens={r['total_tokens']/1e6:.1f}M, "
                  f"best_val={r['best_val_loss']:.4f}")
        if results["nofilter"]["best_val_loss"] != float("inf") and \
           results["filtered"]["best_val_loss"] != float("inf"):
            delta = results["filtered"]["best_val_loss"] - \
                    results["nofilter"]["best_val_loss"]
            pct = delta / results["nofilter"]["best_val_loss"] * 100
            print(f"\n  filtered vs unfiltered: delta val_loss = {delta:+.4f} ({pct:+.1f}%)")
            if delta < 0:
                print("  [OK] cleaning lowered validation loss!")
            else:
                print("  [WARN] cleaning increased loss? check if filtering is too strict")
        print(f"{'='*60}")


if __name__ == "__main__":
    main()
