#!/usr/bin/env python3
"""
══════════════════════════════════════════════════════════════════════
Pre-training filter rule library (imported by the streaming script)
══════════════════════════════════════════════════════════════════════

Filter strategy, layered by severity:

  L1 - framework templates (fatal contamination):
    Django (migrations, models, admin), Plotly validators,
    Flask/FastAPI route boilerplate, SQLAlchemy table defs

  L2 - Python 2 relics:
    # -*- coding, __future__ imports, unicode_literals

  L3 - config / license / boilerplate:
    sphinx_conf + packaging - fatal (whole file is config)
    copyright/SPDX/shebang - strip header comments, keep code

  L4 - test files:
    unittest, pytest, def test_, def setUp, def tearDown,
    conftest, test file paths

  L5 - quality metrics:
    import lines >60%, class/decorator >70%, consecutive repeats >=3,
    no function defs, effective lines <3, comment rate >80%

  L6 - autogenerated code:
    long numeric suffixes, UUID patterns, leftover template vars

This file is a rules library for the streaming scripts. Do not run it directly.
══════════════════════════════════════════════════════════════════════
"""

import os, sys, json, re, random, fnmatch
from pathlib import Path
from collections import Counter, defaultdict
from datetime import datetime

# path constants for the old layout: filter.py runs standalone, but tokenizer path now follows repo layout
REPO_ROOT = Path(__file__).resolve().parent.parent.parent  # src/data/ -> repo root/
CODE_LLM_PROJECT = REPO_ROOT.parent / "code-llm-project"  # legacy sibling layout, not shipped
CLEAN_PRETRAIN_DIR = Path(__file__).resolve().parent  # src/data/
print(f"[PATH] this project dir: {CLEAN_PRETRAIN_DIR}")
print(f"[PATH] repo root: {REPO_ROOT}")

# local tokenizer loading (repo tokenizer/ preferred, then legacy fallback)
def load_tokenizer():
    """Load tokenizer: prefer repo tokenizer/ dir, then legacy fallback."""
    from tokenizers import Tokenizer
    candidates = [
        str(REPO_ROOT / "tokenizer" / "tokenizer_435m.json"),
        str(CODE_LLM_PROJECT / "tokenizer" / "tokenizer.json"),
    ]
    for i, tok_path in enumerate(candidates):
        tok = Path(tok_path)
        exists = tok.exists()
        print(f"[TOK] candidate {i+1}: {tok} (exists={exists})")
        if exists and tok.is_file():
            tokenizer = Tokenizer.from_file(tok_path)
            print(f"[TOK] [OK] loaded: vocab={tokenizer.get_vocab_size()}")
            if tokenizer.token_to_id("<pad>") is None:
                tokenizer.add_special_tokens(["<pad>"])
            return tokenizer
    raise FileNotFoundError(f"Tokenizer not found. Searched: {candidates}")

# ═══════════════════════════════════════════════════════════════════
# filter rule definitions
# ═══════════════════════════════════════════════════════════════════

# L1: framework templates (fatal - drop on match)
FRAMEWORK_BOILERPLATE = {
    "django_migration": [
        "migrations.RunPython", "apps.get_model(",
        "class Migration(migrations.Migration)",
        "from django.db import migrations", "schema_editor",
        "migrations.AddField", "migrations.RemoveField",
        "migrations.AlterField", "migrations.CreateModel",
        "migrations.DeleteModel", "migrations.RenameField",
    ],
    "django_model": [
        "models.CharField(", "models.TextField(", "models.IntegerField(",
        "models.BooleanField(", "models.DateField(", "models.DateTimeField(",
        "models.ForeignKey(", "models.OneToOneField(", "models.ManyToManyField(",
        "models.EmailField(", "models.URLField(", "models.FileField(",
        "models.ImageField(", "models.DecimalField(", "models.FloatField(",
        "models.AutoField(", "models.SlugField(", "models.JSONField(",
        "models.UUIDField(",
    ],
    "django_meta": [
        "class Meta:", "verbose_name", "db_table",
        "unique_together", "index_together",
        "ordering =", "permissions =",
    ],
    "django_admin": [
        "admin.ModelAdmin", "admin.site.register",
        "admin.TabularInline", "admin.StackedInline",
        "list_display =", "search_fields =",
        "list_filter =", "admin.register(",
        "class Media:", "class MediaDefiningClass",
    ],
    "django_config": [
        # Django settings.py patterns
        "SECRET_KEY =", "DEBUG = True",
        "DATABASES =", "INSTALLED_APPS =",
        "MIDDLEWARE =", "AUTH_PASSWORD_VALIDATORS",
        "TEMPLATES =", "STATIC_URL =",
        "LANGUAGE_CODE =", "WSGI_APPLICATION =",
        "ROOT_URLCONF =", "ALLOWED_HOSTS =",
        "AUTH_USER_MODEL =", "LOGIN_URL =",
        "REST_FRAMEWORK =", "CELERY_BROKER_URL",
    ],
    "plotly": [
        "_plotly_utils", "basevalidators", "BaseValidator",
        "plotly_name=", "edit_type=", "parent_name=",
        "InfoArrayValidator", "DataArrayValidator",
        "CompoundValidator", "CompoundArrayValidator",
        "EnumeratedValidator", "FlaglistValidator",
        "AnyValidator", "DashValidator",
    ],
    "flask_fastapi": [
        "@app.route(", "@router.get(", "@router.post(",
        "@bp.route(", "@api_view(", "Flask(__name__)",
        "APIRouter(", "FastAPI(",
    ],
    "sqlalchemy_table": [
        "Column(String", "Column(Integer", "Column(Boolean",
        "Column(ForeignKey", "Column(DateTime",
        "declarative_base()", "__tablename__",
        "relationship(", "back_populates",
    ],
    "other_frameworks": [
        "django_filters", "rest_framework",
        "graphene.", "strawberry.",
        "factory_boy", "factory.django",
        "import factory",
    ],
}

# L2: Python 2 relics
PYTHON2_LEGACY = [
    "# -*- coding:", "# -*- coding",
    "#!-*- coding", "#!-*-coding",    # Emacs-style coding variant
    "#coding:", "# coding:",          # bare coding decl
    "from __future__ import",
    "unicode_literals", "print_function",
    "absolute_import", "division",
    "import __builtin__", "basestring",
    "xrange(", "unicode(",
    "print >>",                       # Python 2 print redirect
    "except Exception, e:",           # Python 2 except syntax
]

# L3: config / license / boilerplate
CONFIG_BOILERPLATE = {
    "license": [
        "SPDX-License-Identifier",
        "Copyright (c)", "Copyright (C)",
        "All rights reserved",
        "Licensed under", "LICENSE",
        "GNU General Public License",
        "Apache License", "MIT License",
        "BSD License", "Free Software Foundation",
    ],
    "shebang_config": [
        "#!/usr/bin/env",
        "#!/usr/bin/python",
        "#!/bin/bash", "#!/bin/sh",
    ],
    "sphinx_conf": [
        "extensions = [", "master_doc =",
        "html_theme =", "pygments_style =",
    ],
    "packaging": [
        "from setuptools import", "distutils",
        "setup(", "install_requires=[",
        "entry_points={", "package_data={",
    ],
}

# L4: test files
TEST_PATTERNS = [
    "import unittest", "import pytest",
    "from unittest import", "from pytest import",
    "unittest.TestCase", "pytest.mark.",
    "pytest.fixture", "pytest.raises",
    "def test_", "def setUp(", "def tearDown(",
    "def setUpClass(", "def tearDownClass(",
    "self.assertEqual", "self.assertTrue",
    "self.assertFalse", "self.assertRaises",
    "self.assertIn", "self.assertIsNone",
    "self.assertIsNotNone", "self.assertListEqual",
    "self.assertDictEqual",
    "mock.patch(", "MagicMock", "Mock(",
    "@mock.patch", "@patch(",
]

# L6: autogenerated code
AUTOGEN_PATTERNS = [
    r"\b[a-z]+_\d{4,}\b",           # variable name + long numeric suffix
    r"\b[0-9a-f]{32}\b",             # MD5 hash
    r"\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b",  # UUID
    r"\{\{.*?\}\}",                   # Jinja / template variable
    r"\{% .*?%\}",
]

# filename-level filtering
POISON_FILENAMES = [
    "migrations/", "/tests/", "/test_",
    "setup.py", "conftest.py", "__init__.py", "__main__.py",
    "manage.py", "wsgi.py", "asgi.py",
    "celery.py", "admin.py", "apps.py", "urls.py",
    "conf.py",  # Sphinx
]

POISON_PATH_PATTERNS = [
    "*/migrations/*", "*/tests/*", "*/test/*",
    "*/django/*", "*/plotly/*", "*/flask*",
    "*/setup.py", "*/conftest.py",
]


def is_filename_poison(filepath: str) -> bool:
    """Filename / path-level filtering."""
    for pat in POISON_FILENAMES:
        if pat in filepath:
            return True
    for pat in POISON_PATH_PATTERNS:
        if fnmatch.fnmatch(filepath, pat):
            return True
    return False


def check_l1_framework(code: str) -> tuple:
    """L1: framework template detection - fatal on hit."""
    for category, patterns in FRAMEWORK_BOILERPLATE.items():
        for pat in patterns:
            if pat in code:
                return True, f"L1_{category}:{pat[:60]}"
    return False, ""


def check_l2_python2(code: str) -> tuple:
    """L2: Python 2 relics."""
    for pat in PYTHON2_LEGACY:
        if pat in code:
            return True, f"L2_python2:{pat}"
    return False, ""


def strip_comment_header(code: str) -> str:
    """
    Strip a header comment block containing copyright/license keywords.
    Keep normal comments and docstrings that don't mention copyright.

    Strategy: collect contiguous soft content at the top (shebang, # comments,
    blank lines, docstring, ...), then check the whole block for copyright
    keywords. Strip it all if found, keep it all if not.

    Return the peeled code. If what remains is shorter than 50 chars,
    return the original code instead.
    """
    lines = code.split('\n')
    if not lines:
        return code

    LIC_KEYWORDS = [
        "copyright", "all rights reserved", "licensed under",
        "gnu general public license", "apache license", "mit license",
        "bsd license", "free software foundation", "spdx-license-identifier",
        "this program is free software", "redistribution and use",
        "permission is hereby granted", "this source code",
        "license version", "the free software foundation",
        "distributed under the terms",
    ]

    code_start = 0
    max_rounds = 10

    for _round in range(max_rounds):
        i = code_start
        block_parts = []     # collected text fragments
        has_shebang = False

        while i < len(lines):
            stripped = lines[i].strip()
            s_lower = stripped.lower()

            if s_lower == '':
                # blank line - counts as soft content
                block_parts.append('')
                i += 1
                continue

            if s_lower.startswith('#!'):
                # shebang - always stripped (boilerplate)
                block_parts.append(stripped[2:])
                has_shebang = True
                i += 1
                continue

            if stripped.startswith('#'):
                # # comments - collect content
                block_parts.append(stripped[1:].strip())
                i += 1
                continue

            # check if this is a docstring
            if stripped.startswith('"""') or stripped.startswith("'''"):
                quote = stripped[:3]
                if stripped.count(quote) >= 2 and len(stripped) > 3:
                    # single-line docstring
                    doc_content = stripped[3:-3]
                    block_parts.append(doc_content)
                    i += 1
                else:
                    # multi-line docstring
                    doc_lines = [stripped[3:]] if len(stripped) > 3 else []
                    i += 1
                    doc_found_end = False
                    while i < len(lines):
                        ls = lines[i].strip()
                        if quote in ls:
                            doc_lines.append(ls.replace(quote, ''))
                            i += 1
                            doc_found_end = True
                            break
                        doc_lines.append(lines[i])
                        i += 1
                    if not doc_found_end:
                        break  # unterminated docstring, stop collecting
                    doc_content = '\n'.join(doc_lines)
                    block_parts.append(doc_content)
                continue

            # hit a real code line - stop collecting
            break

        if i == code_start:
            # no soft content collected
            break

        # check whole block for copyright keywords
        block_text = ' '.join(block_parts).lower()
        has_license = any(kw in block_text for kw in LIC_KEYWORDS)

        if has_license or has_shebang:
            code_start = i  # strip the whole block
        else:
            break  # no copyright, keep it, stop the loop

    if code_start >= len(lines):
        return code

    stripped_code = '\n'.join(lines[code_start:]).strip()

    # return if there is content (short code is left to L5 quality filter)
    if stripped_code:
        return stripped_code
    return code



def strip_all_copyright_comments(code: str) -> str:
    """Scan every # comment block in the file; if a block mentions copyright/license
    keywords, strip the whole block. Never reject the file - only comments go,
    the code stays. Also handles repeated header stripping."""
    LIC_KEYWORDS = [
        "copyright", "all rights reserved", "licensed under",
        "gnu general public license", "apache license", "mit license",
        "bsd license", "free software foundation", "spdx-license-identifier",
        "this program is free software", "redistribution and use",
        "permission is hereby granted", "this source code",
        "license version", "the free software foundation",
        "distributed under the terms",
    ]

    # Step 1: multi-round header stripping (top # comments + docstring)
    code = strip_comment_header(code)

    # Step 2: scan all # comment blocks, strip any with copyright keywords
    lines = code.split('\n')
    to_remove = set()
    i = 0
    while i < len(lines):
        stripped = lines[i].strip()
        if stripped.startswith('#'):
            # collect contiguous # comment block
            block_start = i
            block_lines = []
            while i < len(lines):
                s = lines[i].strip()
                if s.startswith('#'):
                    block_lines.append(s[1:].strip())  # drop the #
                    i += 1
                elif s == '':
                    block_lines.append('')
                    i += 1
                else:
                    break
            block_end = i
            block_text = ' '.join(block_lines).lower()

            # check the whole block for copyright keywords
            if any(kw in block_text for kw in LIC_KEYWORDS):
                for j in range(block_start, block_end):
                    to_remove.add(j)
            continue
        i += 1

    if not to_remove:
        return code

    # delete marked lines, also collapse the resulting blank runs
    kept = []
    prev_empty = False
    for idx, line in enumerate(lines):
        if idx in to_remove:
            continue
        is_empty = line.strip() == ''
        if is_empty and prev_empty:
            continue  # collapse consecutive blank lines
        kept.append(line)
        prev_empty = is_empty

    result = '\n'.join(kept).strip()

    # return if content remains (short code goes to the quality filter)
    if result:
        return result
    return code


def check_l3_config(code: str) -> tuple:
    """L3: config / license - two cases:
      - license + shebang: strippable (peel the header comments, re-check)
      - sphinx_conf + packaging: fatal (whole file is config)"""
    for pat in CONFIG_BOILERPLATE.get("sphinx_conf", []) + CONFIG_BOILERPLATE.get("packaging", []):
        if pat in code:
            return True, f"L3_fatal:{pat[:60]}"
    # license/shebang are no longer fatal here - stripped in extract instead
    return False, ""


def check_l4_tests(code: str) -> tuple:
    """L4: test files"""
    for pat in TEST_PATTERNS:
        if pat in code:
            return True, f"L4_test:{pat}"
    return False, ""


def check_l6_autogen(code: str) -> tuple:
    """L6: autogenerated code"""
    for pat in AUTOGEN_PATTERNS:
        # cap matches for some patterns (avoid false positives on normal code)
        matches = re.findall(pat, code)
        if len(matches) >= 3:
            return True, f"L6_autogen:{pat}({len(matches)} hits)"
    return False, ""


def compute_quality_metrics(code: str) -> tuple:
    """
    L5: quality metrics
    Returns (pass: bool, reason: str)
    """
    lines = code.split('\n')
    total = len(lines)
    if total < 2:
        return False, "too_few_lines"

    # non-empty, non-comment-only lines
    non_comment = [l for l in lines if l.strip() and not l.strip().startswith('#')]
    effective = len(non_comment)
    if effective < 2:
        return False, f"effective_lines={effective}"

    # import line ratio
    import_count = sum(1 for l in non_comment
                       if l.strip().startswith(('import ', 'from ')))
    import_ratio = import_count / effective if effective > 0 else 1
    if import_ratio > 0.6:
        return False, f"import_ratio={import_ratio:.0%}"

    # class/decorator ratio
    class_count = sum(1 for l in non_comment
                      if l.strip().startswith(('class ', '@staticmethod', '@classmethod', '@property')))
    decorator_count = sum(1 for l in non_comment
                          if l.strip().startswith('@') and not l.strip().startswith(('@staticmethod', '@classmethod', '@property')))
    class_ratio = (class_count + decorator_count) / effective if effective > 0 else 0
    if class_ratio > 0.7:
        return False, f"class_ratio={class_ratio:.0%}"

    # comment ratio
    comment_lines = sum(1 for l in lines if l.strip().startswith('#'))
    comment_ratio = comment_lines / total if total > 0 else 0
    if comment_ratio > 0.8:
        return False, f"comment_ratio={comment_ratio:.0%}"

    # function defs (must have at least one, with logic lines after)
    has_def = False
    def_idx = -1
    for i, l in enumerate(non_comment):
        if l.strip().startswith('def '):
            has_def = True
            def_idx = i
            # check def is followed by logic lines (not pure pass/return placeholders)
            has_body = False
            for j in range(i + 1, min(i + 5, len(non_comment))):
                body = non_comment[j].strip()
                if body and body != 'pass' and not body.startswith('"""'):
                    has_body = True
                    break
            if not has_body and "raise NotImplementedError" not in non_comment[i]:
                return False, "def_without_body"

    if not has_def:
        # if no def, check there is effective logic (not pure config)
        logic_lines = sum(1 for l in non_comment
                         if any(kw in l for kw in ['=', 'if ', 'for ', 'while ', 'return ', 'print(', 'yield ']))
        if logic_lines < 2:
            return False, "no_def_no_logic"

    # consecutive duplicate lines
    stripped = [l.strip() for l in non_comment]
    consec = 0
    for i in range(1, len(stripped)):
        if stripped[i] == stripped[i-1] and stripped[i]:
            consec += 1
            if consec >= 3:
                return False, "consecutive_repeated_lines"
        else:
            consec = 0

    # mean line length (anomaly signal)
    avg_len = sum(len(l) for l in non_comment) / max(effective, 1)
    if avg_len < 8:
        return False, f"avg_line_len={avg_len:.0f}"

    return True, "ok"


# ═══════════════════════════════════════════════════════════════════

def verify_clean_data(jsonl_path, poison_patterns=None, sample_size=100):
    """
    Check the extracted JSONL for residual contamination.
    Sample-print normal vs suspicious code.
    """
    if poison_patterns is None:
        # most dangerous poison patterns (rare to hit, huge harm)
        poison_patterns = [
            ("DjangoMigration", "class Migration(migrations.Migration)"),
            ("DjangoRunPython", "migrations.RunPython"),
            ("DjangoModel", "models.CharField("),
            ("PlotlyValidator", "_plotly_utils.basevalidators"),
            ("PlotlyPlotlyName", "plotly_name="),
            ("Python2Coding", "# -*- coding:"),
            ("Python2Future", "from __future__ import"),
            ("Unittest", "unittest.TestCase"),
            ("Pytest", "pytest.mark."),
            ("Setuptools", "from setuptools import"),
        ]

    print(f"\n{'='*60}")
    print(f"[INFO] verifying data quality: {jsonl_path}")
    print(f"{'='*60}")

    all_codes = []
    with open(jsonl_path, "r", encoding="utf-8") as f:
        for line in f:
            item = json.loads(line)
            text = item.get("text", "")
            if text:
                all_codes.append(text)

    print(f"  total rows: {len(all_codes):,}")

    # check each poison pattern
    total_hits = 0
    for label, pattern in poison_patterns:
        hits = sum(1 for code in all_codes if pattern in code)
        if hits > 0:
            print(f"  [WARN]  {label}: {hits} rows ({hits/len(all_codes)*100:.3f}%)")
            total_hits += hits

    if total_hits == 0:
        print(f"  [OK] zero contamination - none of {len(poison_patterns)} patterns hit")
    else:
        print(f"  [FAIL] {total_hits} contaminated rows remain ({total_hits/len(all_codes)*100:.2f}%)")

    # random sample of normal code
    print(f"\n{'─'*50}")
    print(f"[WRITE] random sample of normal code (5 of the first {sample_size} rows):")
    print(f"{'─'*50}")
    random.seed(42)
    samples = random.sample(all_codes, min(sample_size, len(all_codes)))
    for i, code in enumerate(samples[:5]):
        first_line = code.split('\n')[0].strip()[:80]
        n_lines = len(code.split('\n'))
        n_chars = len(code)
        print(f"\n  [{i+1}] {n_chars} chars, {n_lines} lines")
        print(f"  {first_line}...")
        # show the snippet
        for line in code.split('\n')[1:6]:
            print(f"    {line[:100]}")

    return total_hits


# ═══════════════════════════════════════════════════════════════════
# pre-tokenization
# ═══════════════════════════════════════════════════════════════════

def pre_tokenize_jsonl(input_path, output_bin, tokenizer, seq_len=1024):
    """JSONL -> .bin (mmap-compatible). Memory-friendly: uses array H instead of list."""
    import numpy as np
    from array import array
    from tqdm import tqdm

    texts = []
    with open(input_path, "r", encoding="utf-8") as f:
        for line in f:
            item = json.loads(line)
            if "text" in item:
                texts.append(item["text"] + "<eos>")
            elif "prompt" in item and "solution" in item:
                texts.append(item["prompt"] + item["solution"] + "<eos>")

    if not texts:
        print(f"  [FAIL] empty file: {input_path}")
        return

    n_texts = len(texts)
    print(f"  [WRITE] {n_texts:,} texts, tokenizing...")

    all_ids = array('H')
    batch_size = 256
    pbar = tqdm(total=n_texts, desc=f"  Tokenizing {Path(input_path).name}",
                unit="text", unit_scale=True)
    for i in range(0, n_texts, batch_size):
        batch = texts[i:i + batch_size]
        for enc in tokenizer.encode_batch(batch):
            ids_list = enc.ids
            max_id = max(ids_list) if ids_list else 0
            if max_id > 65535:
                raise ValueError(
                    f"Token ID {max_id} exceeds uint16 range (vocab={tokenizer.get_vocab_size()})."
                    f"  use uint32 or a smaller vocab."
                )
            all_ids.fromlist(ids_list)
        pbar.update(len(batch))
    pbar.close()

    total_tokens = (len(all_ids) // seq_len) * seq_len
    print(f"  [NUM] {len(all_ids):,} raw tokens -> truncate to {total_tokens:,} ({total_tokens/1e6:.1f}M)")

    ids_array = np.frombuffer(all_ids[:total_tokens], dtype=np.uint16).copy()
    ids_array.tofile(output_bin)

    # metadata
    meta = {
        "total_tokens": total_tokens,
        "vocab_size": tokenizer.get_vocab_size(),
        "seq_len": seq_len,
        "source": str(input_path),
        "dtype": "uint16",
        "created": datetime.now().isoformat(),
    }
    meta_path = str(output_bin).replace(".bin", "_meta.json")
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)

    file_size_mb = Path(output_bin).stat().st_size / 1e6
    print(f"  [OK] {total_tokens:,} tokens ({total_tokens/1e6:.1f}M), {file_size_mb:.1f} MB")

